### ISSUE TITLE
Wave mini?

### ISSUE THREAD

**Issue by 6zXo8aMn2TRXOs** [anaxyd/homey-airthings#1]
Hey!
Do you have any plans to add wave mini? Am just interested in measuring TVOC, so I don't need a more advanced sensor. If I buy one, can I help you in anyway with the support?

Hälsningar från Sverige, ha!

**Comment by anaxyd** [comment]
Hey @rindlerblabla!

Absolutely! But since it has just released, Airthings do not have any documentation on it yet. They have done that on the Wave and Wave Plus, which is the base for all integrations with those devices. :-)

https://github.com/Airthings

As soon as they release one for the Mini too, we can examine the code and try to make a integration!

Hei fra Norge! :-)

**Comment by rindlerblabla** [comment]
Was in contact with Airthings support and they said they have no plans (/manpower) to add mini to their github-project. Instead they're referring to their coming Hub and that they will then open up a REST api which would communicate through their cloud. Am not really interested in another controller/hub...

**Comment by rindlerblabla** [comment]
No rush, but out of curiosity. Do you know anything more when the mini can be supported?

**Comment by anaxyd** [comment]
> No rush, but out of curiosity. Do you know anything more when the mini can be supported?

Hey! We are actually working with Airthings as we speak to implement Wave and Wave Mini. Wave will be added this week, and after that Mini will be added. :-)

**Comment by anaxyd** [comment]
We have released a new version of the app now which supports Wave, here is the link to try it out:

https://homey.app/a/com.airthings/test/

**Comment by rindlerblabla** [comment]
Solved with pull request https://github.com/anaxyd/homey-airthings/pull/6
